name: DevSecOps

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build an image from Dockerfile
        run: |
          docker build -t appsecengineer/vulnerable-app:${{ github.sha }} .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'appsecengineer/vulnerable-app:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
  sca:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Setup Python 3.11.6
        uses: actions/setup-python@v4
        with: 
          python-version: 3.11.6
      - name: Install python deps
        run: |
          python -m pip install --upgrade pip
          pip install pyraider==1.0.20
      - name: Get working directory
        run: echo $(PWD)
      - name: Scan packages
        run: |
          pyraider check -f ./app/requirements.txt -e json ./app/result.json
      - name: "Upload Report"
        uses: actions/upload-artifact@v1
        with:
          name: pyraider-scan-report
          path: ./app/result.json
  dast:
    if: always()
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Setup Python 3.11.6
        uses: actions/setup-python@v4
        with: 
          python-version: 3.11.6
      - name: Install python deps
        run: |
          python -m pip install --upgrade pip
          pip install requests python-owasp-zap-v2.4
      - name: Get working directory
        run: echo $(PWD)
      - name: Install OWASP ZAP
        run: |
          mkdir -p ./zap
          cd ./zap
          wget -N https://github.com/zaproxy/zaproxy/releases/download/v2.9.0/ZAP_2.9.0_Linux.tar.gz
          tar -zxvf ZAP_2.9.0_Linux.tar.gz
          rm ZAP_2.9.0_Linux.tar.gz
          cd ZAP_2.9.0/plugin
          wget https://github.com/zaproxy/zap-extensions/releases/download/exportreport-v6/exportreport-alpha-6.zap
          echo 'export PATH_ZAP_SH=./zap/ZAP_2.9.0/zap.sh' >> ~/.bashrc
          echo 'export ZAP_PORT=8090' >> ~/.bashrc
          echo 'sh -c "$PATH_ZAP_SH -daemon -host 0.0.0.0 -port $ZAP_PORT -configfile ./zap/ZAP_2.9.0/conf" > /dev/null & ' > start-zap
          echo 'sleep 40' >> start-zap
          echo 'sh -c "$PATH_ZAP_SH -host 0.0.0.0 -port $ZAP_PORT -configfile ./zap/ZAP_2.9.0/conf" > /dev/null & ' > start-gui-zap
          echo 'sleep 40' >> start-gui-zap
          echo 'pkill -f zap' > stop-zap
          chmod +x start-zap
          chmod +x start-gui-zap
          chmod +x stop-zap
          echo $pwd
      - name: Run Docker Container
        run: docker run -d -p 5050:5050 we45/vul_flask:latest
      - name: Run ZAP Daemon
        run: ./zap/ZAP_2.9.0/zap.sh -daemon -host 0.0.0.0 -port 8090 -config api.addrs.addr.name=".*" -config api.addrs.addr.regex=true -config api.disablekey=true > /dev/null &
      - name: Sleep for a bit
        uses: jakejarvis/wait-action@master
        with:
          time: '20s'
      - name: Run Test Automation with ZAP
        run: |
          cd ./tests/
          python e2e_zap.py
      - name: "Upload Report"
        uses: actions/upload-artifact@v1
        with:
          name: zap-scan-report
          path: ./tests/zap-report.json
